# Generated by Django 3.1.7 on 2021-04-07 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vacancy', '0002_auto_20210405_2207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('not_looking', 'Не ищу работу'), ('taking_offers', 'Рассматриваю предложения'), ('looking', 'Ищу работу')], max_length=20)),
                ('salary', models.IntegerField(default=0)),
                ('grade', models.CharField(choices=[('intern', 'Стажер'), ('junior', 'Джуниор'), ('middle', 'Миддл'), ('senior', 'Синьор'), ('lead', 'Лид')], max_length=10)),
                ('education', models.TextField()),
                ('experience', models.TextField()),
                ('portfolio', models.URLField(blank=True, default='', max_length=120)),
                ('specialty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resume', to='vacancy.specialty')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resume', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
